# Generated by Django 4.2.7 on 2024-05-26 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rename_menu_menuitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='tiptle',
            new_name='title',
        ),
    ]
